<?php
#
# File generated by Dolibarr installer 3.1.1 on 2012-05-16 16:05:03
#
# Take a look at conf.php.example file for an example of conf.php file
# and explanations for all possibles parameters.
#
$dolibarr_main_url_root='http://cormoranarica.no-ip.org/test/htdocs';
$dolibarr_main_document_root='/var/www/test/htdocs';
#$dolibarr_main_url_root_alt='http://cormoranarica.no-ip.org/test/htdocs/custom';
#$dolibarr_main_document_root_alt='/var/www/test/htdocs/custom';
$dolibarr_main_data_root='/var/www/test/documents';
$dolibarr_main_db_host='localhost';
$dolibarr_main_db_port='3306';
$dolibarr_main_db_name='test_db';
$dolibarr_main_db_user='test-user';
$dolibarr_main_db_pass='gambess';
$dolibarr_main_db_type='mysqli';
$dolibarr_main_db_character_set='utf8';
$dolibarr_main_db_collation='utf8_general_ci';
$dolibarr_main_authentication='dolibarr';

# Specific settings
$dolibarr_main_prod='0';
$dolibarr_nocsrfcheck='0';
$dolibarr_main_force_https='0';
$dolibarr_main_cookie_cryptkey='96803a8ca4041052ed2a3a69b3308f4f';
$dolibarr_mailing_limit_sendbyweb='0';
?>